<?xml version="1.0"?>
<MPD xmlns="(http://aya-streamer2.cdn.3bbtv.com:8080/3bb/live/101/101.mpd)" type="static" ID="test.m3u8" mediaPresentationDuration="PT00H00M14.00S" minBufferTime="PT00H00M1.50S">
 <ProgramInformation moreInformationURL="http://gpac.sourceforge.net">
  <Title>test.m3u8</Title>
  <Source>Generated from URL test.m3u8</Source>
  <Copyright>Generated by GPAC 0.5.2-DEV-rev649-g361314a-master from test.m3u8</Copyright>
 </ProgramInformation>
 <Period duration="PT00H00M0.00S">
  <AdaptationSet segmentAlignment="true">
   <Representation id="test.m3u8" bandwidth="341708" width="640" height="480" audioSamplingRate="44100" mimeType="video/mp2t" codecs="avc1.42801e,mp4a.40.02">
   <SegmentList duration="5000" startNumber="0"/>
   <SegmentURL media="0.ts"/>
/>
   <SegmentURL media="1.ts"/>
/>
   <SegmentURL media="2.ts"/>
/>
   </SegmentList>
   </Representation>
  </AdaptationSet>
 </Period>
</MPD>
